version: "3.9"

services:
  crm-ui:
    image: ghcr.io/olli-suoniemi/wigcrm/ui:latest
    environment:
      ENV: production 
    depends_on:
      - crm-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crm-ui.rule=Host(`crm.olli.codes`)"
      - "traefik.http.routers.crm-ui.entrypoints=websecure"
      - "traefik.http.routers.crm-ui.tls.certresolver=myresolver"
      - "traefik.http.services.crm-ui.loadbalancer.server.port=3000"

      # Define HSTS middleware
      - "traefik.http.middlewares.hsts.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.hsts.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.hsts.headers.stsPreload=true"

      # Attach HSTS middleware to this router
      - "traefik.http.routers.crm-ui.middlewares=hsts"
    networks:
      - internal
      - proxy
    deploy:
      update_config:
        order: start-first
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 30s

  crm-api:
    image: ghcr.io/olli-suoniemi/wigcrm/api:latest
    depends_on:
      - database
      - flyway
      - redis
    environment:
      CRM_PGUSER_FILE: /run/secrets/CRM_PGUSER
      CRM_PGPASSWORD_FILE: /run/secrets/CRM_PGPASSWORD
      CRM_PGDATABASE_FILE: /run/secrets/CRM_PGDATABASE
      CRM_PGHOST_FILE: /run/secrets/CRM_PGHOST
      CRM_PGPORT_FILE: /run/secrets/CRM_PGPORT
    secrets:
      - CRM_PGUSER
      - CRM_PGPASSWORD
      - CRM_PGDATABASE
      - CRM_PGHOST
      - CRM_PGPORT
      - CRM_FIREBASE_SERVICE_JSON
      - CRM_ADMIN_IDS
      - CRM_FORWARD_EMAIL_API_KEY
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crm-api.rule=Host(`crm.olli.codes`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.crm-api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.crm-api.middlewares=crm-api-stripprefix"
      - "traefik.http.routers.crm-api.entrypoints=websecure"
      - "traefik.http.routers.crm-api.tls.certresolver=myresolver"
      - "traefik.http.services.crm-api.loadbalancer.server.port=7777"
    networks:
      - internal
      - proxy
    deploy:
      update_config:
        order: start-first
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 30s

  redis:
    image: redis:latest
    command: >
      redis-server --maxmemory 500mb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
    networks:
      - internal

  database:
    image: postgres:16.1
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - CRM_POSTGRES_USER
      - CRM_POSTGRES_PASSWORD
      - CRM_POSTGRES_DB
    environment:
      POSTGRES_USER_FILE: /run/secrets/CRM_POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/CRM_POSTGRES_PASSWORD
      POSTGRES_DB_FILE: /run/secrets/CRM_POSTGRES_DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d `cat $$POSTGRES_DB_FILE` -U `cat $$POSTGRES_USER_FILE`" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal


  flyway:
    image: ghcr.io/olli-suoniemi/wigcrm/flyway:latest
    depends_on:
      - database
    environment:
      FLYWAY_USER_FILE: /run/secrets/FLYWAY_USER
      FLYWAY_PASSWORD_FILE: /run/secrets/FLYWAY_PASSWORD
      CRM_FLYWAY_URL_FILE: /run/secrets/CRM_FLYWAY_URL
    secrets:
      - FLYWAY_USER
      - FLYWAY_PASSWORD
      - CRM_FLYWAY_URL
    networks:
      - internal
    deploy:
      restart_policy:
        condition: none 

volumes:
  db-data:
  flyway-sql:
    driver: local 

secrets:
  CRM_PGUSER:
    external: true
  CRM_PGPASSWORD:
    external: true
  CRM_PGDATABASE:
    external: true
  CRM_PGHOST:
    external: true
  CRM_PGPORT:
    external: true

  CRM_POSTGRES_USER:
    external: true
  CRM_POSTGRES_PASSWORD:
    external: true
  CRM_POSTGRES_DB:
    external: true

  FLYWAY_USER:
    external: true
  FLYWAY_PASSWORD:
    external: true
  CRM_FLYWAY_URL:
    external: true 

  CRM_ADMIN_IDS:
    external: true
  CRM_FIREBASE_SERVICE_JSON:
    external: true
  CRM_FORWARD_EMAIL_API_KEY:
    external: true

  

networks:
  proxy:
    external: true
  internal:
    driver: overlay